In [1]:
import pandas as pd

calc_train_df = pd.read_csv('../data_description/calc_case_description_train_set.csv')
mass_train_df = pd.read_csv('../data_description/mass_case_description_train_set.csv')

In [2]:
calc_train_df.head()

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00005,3,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...
1,P_00005,3,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....
2,P_00007,4,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...
3,P_00007,4,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...
4,P_00008,1,LEFT,CC,1,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...

In [3]:
mass_train_df.head()

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00001,3,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...
1,P_00001,3,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...
2,P_00004,3,LEFT,CC,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00004_LEFT_CC_1/1.3.6.1.4.1.95...
3,P_00004,3,LEFT,MLO,1,mass,ARCHITECTURAL_DISTORTION,ILL_DEFINED,4,BENIGN,3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00004_LEFT_MLO_1/1.3.6.1.4.1.9...
4,P_00004,3,RIGHT,MLO,1,mass,OVAL,CIRCUMSCRIBED,4,BENIGN,5,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....,Mass-Training_P_00004_RIGHT_MLO_1/1.3.6.1.4.1....

In [4]:
df = pd.concat([calc_train_df, mass_train_df], ignore_index=True)

df.head()

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,breast_density,mass shape,mass margins
0,P_00005,3.0,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,NaN,NaN,NaN
1,P_00005,3.0,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,NaN,NaN,NaN
2,P_00007,4.0,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,NaN,NaN,NaN
3,P_00007,4.0,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,NaN,NaN,NaN
4,P_00008,1.0,LEFT,CC,1,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,NaN,NaN,NaN

In [5]:
df['pathology'].unique()

<StringArray>
['MALIGNANT', 'BENIGN', 'BENIGN_WITHOUT_CALLBACK']
Length: 3, dtype: str

In [6]:
df['pathology'] = df['pathology'].replace({
    'BENIGN_WITHOUT_CALLBACK': 'BENIGN'
})

df['pathology'].unique()

<StringArray>
['MALIGNANT', 'BENIGN']
Length: 2, dtype: str

In [7]:
df.head()

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,breast_density,mass shape,mass margins
0,P_00005,3.0,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,NaN,NaN,NaN
1,P_00005,3.0,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,NaN,NaN,NaN
2,P_00007,4.0,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,NaN,NaN,NaN
3,P_00007,4.0,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,NaN,NaN,NaN
4,P_00008,1.0,LEFT,CC,1,calcification,NaN,REGIONAL,2,BENIGN,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,NaN,NaN,NaN

In [8]:
df['pathology'] = df['pathology'].map({'BENIGN': 0, 'MALIGNANT': 1})
df.head()

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,breast_density,mass shape,mass margins
0,P_00005,3.0,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,1,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.959...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9...,NaN,NaN,NaN
1,P_00005,3.0,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,1,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.95...,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1....,NaN,NaN,NaN
2,P_00007,4.0,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,0,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.95...,NaN,NaN,NaN
3,P_00007,4.0,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,0,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.959...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9...,NaN,NaN,NaN
4,P_00008,1.0,LEFT,CC,1,calcification,NaN,REGIONAL,2,0,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.95...,NaN,NaN,NaN

In [9]:
calc_test_df = pd.read_csv('../data_description/calc_case_description_test_set.csv')
mass_test_df = pd.read_csv('../data_description/mass_case_description_test_set.csv')

test_df = pd.concat([calc_test_df, mass_test_df], ignore_index=True)

test_df['pathology'] = test_df['pathology'].replace({
    'BENIGN_WITHOUT_CALLBACK': 'BENIGN'
})

test_df['pathology'] = test_df['pathology'].map({'BENIGN': 0, 'MALIGNANT': 1})

test_df.head()

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,breast_density,mass shape,mass margins
0,P_00038,2.0,LEFT,CC,1,calcification,PUNCTATE-PLEOMORPHIC,CLUSTERED,4,0,2,Calc-Test_P_00038_LEFT_CC/1.3.6.1.4.1.9590.100...,Calc-Test_P_00038_LEFT_CC_1/1.3.6.1.4.1.9590.1...,Calc-Test_P_00038_LEFT_CC_1/1.3.6.1.4.1.9590.1...,NaN,NaN,NaN
1,P_00038,2.0,LEFT,MLO,1,calcification,PUNCTATE-PLEOMORPHIC,CLUSTERED,4,0,2,Calc-Test_P_00038_LEFT_MLO/1.3.6.1.4.1.9590.10...,Calc-Test_P_00038_LEFT_MLO_1/1.3.6.1.4.1.9590....,Calc-Test_P_00038_LEFT_MLO_1/1.3.6.1.4.1.9590....,NaN,NaN,NaN
2,P_00038,2.0,RIGHT,CC,1,calcification,VASCULAR,NaN,2,0,5,Calc-Test_P_00038_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_00038_RIGHT_CC_1/1.3.6.1.4.1.9590....,Calc-Test_P_00038_RIGHT_CC_1/1.3.6.1.4.1.9590....,NaN,NaN,NaN
3,P_00038,2.0,RIGHT,CC,2,calcification,VASCULAR,NaN,2,0,5,Calc-Test_P_00038_RIGHT_CC/1.3.6.1.4.1.9590.10...,Calc-Test_P_00038_RIGHT_CC_2/1.3.6.1.4.1.9590....,Calc-Test_P_00038_RIGHT_CC_2/1.3.6.1.4.1.9590....,NaN,NaN,NaN
4,P_00038,2.0,RIGHT,MLO,1,calcification,VASCULAR,NaN,2,0,5,Calc-Test_P_00038_RIGHT_MLO/1.3.6.1.4.1.9590.1...,Calc-Test_P_00038_RIGHT_MLO_1/1.3.6.1.4.1.9590...,Calc-Test_P_00038_RIGHT_MLO_1/1.3.6.1.4.1.9590...,NaN,NaN,NaN

In [10]:
train_patients = set(df['patient_id'])
test_patients = set(test_df['patient_id'])

overlap = train_patients.intersection(test_patients)

print(len(overlap))
print(overlap)

31
{'P_00394', 'P_01179', 'P_01605', 'P_00495', 'P_00041', 'P_00723', 'P_01237', 'P_00678', 'P_01621', 'P_00159', 'P_00882', 'P_00906', 'P_01566', 'P_01365', 'P_01635', 'P_01803', 'P_01152', 'P_00969', 'P_00510', 'P_00753', 'P_01467', 'P_00591', 'P_00639', 'P_00016', 'P_01741', 'P_01307', 'P_00924', 'P_01108', 'P_00652', 'P_00601', 'P_01883'}

In [11]:
df.drop(df[df['patient_id'].isin(overlap)].index, inplace=True)

In [12]:
train_patients = set(df['patient_id'])
test_patients = set(test_df['patient_id'])

overlap = train_patients.intersection(test_patients)

print(len(overlap))
print(overlap)

0
set()

In [13]:
total = len(df) + len(test_df)

print("Total:", total)
print(f"Train {len(df)} | {len(df)/total*100:.2f}%" )
print(f"Test {len(test_df)} | {len(test_df)/total*100:.2f}%" )

Total: 3485
Train 2781 | 79.80%
Test 704 | 20.20%

In [14]:
# Check for missing values in the datasets
print("Missing values in training dataset:")
print(df.isnull().sum())

Missing values in training dataset:
patient_id                    0
breast density             1291
left or right breast          0
image view                    0
abnormality id                0
abnormality type              0
calc type                  1311
calc distribution          1645
assessment                    0
pathology                     0
subtlety                      0
image file path               0
cropped image file path       0
ROI mask file path            0
breast_density             1490
mass shape                 1494
mass margins               1531
dtype: int64

In [15]:
print("Missing values in test dataset:")
print(test_df.isnull().sum())

Missing values in test dataset:
patient_id                   0
breast density             378
left or right breast         0
image view                   0
abnormality id               0
abnormality type             0
calc type                  382
calc distribution          441
assessment                   0
pathology                    0
subtlety                     0
image file path              0
cropped image file path      0
ROI mask file path           0
breast_density             326
mass shape                 326
mass margins               343
dtype: int64

In [ ]:
pd.set_option("display.max_colwidth", None)
df['image file path']

0         Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm
1       Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/000000.dcm
2         Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/000000.dcm
3        Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/000000.dcm
4         Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm
                                                                                            ...
2859     Mass-Training_P_02033_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.96404273311485845838623929652892337767/1.3.6.1.4.1.9590.100.1.2.399742535611893168217294560510610315389/000000.dcm
2860     Mass-Training_P_02079_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.268797464411367674311421201011804739196/1.3.6.1.4.1.9590.100.1.2.174087037012311934636262526800138239589/000000.dcm
2861     Mass-Training_P_02079_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.79168706212562046504764996222502629838/1.3.6.1.4.1.9590.100.1.2.412558050811722685411988228462651590663/000000.dcm
2862      Mass-Training_P_02092_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.420341693811920799600818661313506180250/1.3.6.1.4.1.9590.100.1.2.150311422512072857220647947940958267422/000000.dcm
2863     Mass-Training_P_02092_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.322851018411213611731661082961359065216/1.3.6.1.4.1.9590.100.1.2.290251769212905477734669932883242291615/000000.dcm
Name: image file path, Length: 2781, dtype: str

In [17]:
from pathlib import Path
import numpy as np

num_images = 0
missing_images = np.array([])

for path in df['image file path']:

    relative = Path(path)

    # Remove the placeholder filename
    folder = Path("../cbis_ddsm_png") / relative.parent

    png_files = list(folder.glob("*.png"))

    if len(png_files) == 0:
        print(f"No PNG files found in {folder}")
        missing_images = np.append(missing_images, path)
        continue

    num_images += 1

No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00005_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157\1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00005_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338\1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00007_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222\1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00007_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887\1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189\1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189\1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189\1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663\1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663\1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663\1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.107045919512740883041445065473029564555\1.3.6.1.4.1.9590.100.1.2.22623043712768131109740179664004028729
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.107045919512740883041445065473029564555\1.3.6.1.4.1.9590.100.1.2.22623043712768131109740179664004028729
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.107045919512740883041445065473029564555\1.3.6.1.4.1.9590.100.1.2.22623043712768131109740179664004028729
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.107045919512740883041445065473029564555\1.3.6.1.4.1.9590.100.1.2.22623043712768131109740179664004028729
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.107045919512740883041445065473029564555\1.3.6.1.4.1.9590.100.1.2.22623043712768131109740179664004028729
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.409130800612759052300668809494105321704\1.3.6.1.4.1.9590.100.1.2.101743131510015201839523365310215332980
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.409130800612759052300668809494105321704\1.3.6.1.4.1.9590.100.1.2.101743131510015201839523365310215332980
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.409130800612759052300668809494105321704\1.3.6.1.4.1.9590.100.1.2.101743131510015201839523365310215332980
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.409130800612759052300668809494105321704\1.3.6.1.4.1.9590.100.1.2.101743131510015201839523365310215332980
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00008_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.409130800612759052300668809494105321704\1.3.6.1.4.1.9590.100.1.2.101743131510015201839523365310215332980
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00010_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.407563183711621278003163718900991700045\1.3.6.1.4.1.9590.100.1.2.271665327610523966032056303433070740031
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00010_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.26432225411287089319376928502511711153\1.3.6.1.4.1.9590.100.1.2.138089954813057214218822588283956286942
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00011_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.276155542712021701434787721271107268211\1.3.6.1.4.1.9590.100.1.2.389208391412680785736990872734216560014
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00011_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.226101260211733383431616492821244251459\1.3.6.1.4.1.9590.100.1.2.121177287111311333525188386730741141286
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00012_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.41801183312109695302459926162531744292\1.3.6.1.4.1.9590.100.1.2.97980732212593010616197208512945314995
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00012_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.312602420012916946632859434732074583789\1.3.6.1.4.1.9590.100.1.2.307271664512650974022213502811472047069
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00013_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.42338003413067189920718816374279625255\1.3.6.1.4.1.9590.100.1.2.255137593013925166616863669013323358727
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00014_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.356512945711558661035394607423245971473\1.3.6.1.4.1.9590.100.1.2.223898792711166317117028681443870663410
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00014_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.357706073312614998302753253342796714335\1.3.6.1.4.1.9590.100.1.2.365997488611944218017486419344205403717
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00019_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.402862878710879755318440884650362135937\1.3.6.1.4.1.9590.100.1.2.211427675111583558805605682400609571318
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00019_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.86372204413773963300916773660922384889\1.3.6.1.4.1.9590.100.1.2.326956207912458716509788527682547540915
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00020_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.94638648511513340427968278020357855320\1.3.6.1.4.1.9590.100.1.2.153128347813213947224177706732042659268
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00020_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.2382334511180002731736037621676649334\1.3.6.1.4.1.9590.100.1.2.375674998311057227230516729621119693765
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00022_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.26048586011838999619697470803489754112\1.3.6.1.4.1.9590.100.1.2.24368093313180939040871774012013458310
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00022_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.198596134813889580735908276893369792931\1.3.6.1.4.1.9590.100.1.2.48194957612266309424978320751888077522
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00024_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.73315536511074306334196798871768995089\1.3.6.1.4.1.9590.100.1.2.397804062110838057908993345582718463885
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00024_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.125949998012485756404023679032358913996\1.3.6.1.4.1.9590.100.1.2.124903870811866529208918844773289609447
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00028_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.43782707412115361525617363602457775937\1.3.6.1.4.1.9590.100.1.2.384733400713300334228962042161417756433
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00029_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.322363293511149457511441419560766495083\1.3.6.1.4.1.9590.100.1.2.17808023811916375736730464253632504086
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00029_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.177960697110436492439838695784087917161\1.3.6.1.4.1.9590.100.1.2.159721624211840137932472262611105662911
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00030_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.277450526512524450123128213833451240023\1.3.6.1.4.1.9590.100.1.2.231380228412044580229454614280746403429
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00030_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.277450526512524450123128213833451240023\1.3.6.1.4.1.9590.100.1.2.231380228412044580229454614280746403429
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00030_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.36125268511964688142424188710430995489\1.3.6.1.4.1.9590.100.1.2.378637774911181109017340773404018176403
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00030_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.36125268511964688142424188710430995489\1.3.6.1.4.1.9590.100.1.2.378637774911181109017340773404018176403
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00030_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.298761075711316947234552995150655234303\1.3.6.1.4.1.9590.100.1.2.298477783611607430420740660610178234342
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00030_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.423205417111965408516647709462910421014\1.3.6.1.4.1.9590.100.1.2.8224011612206957419584270413389091077
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00031_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.423368663612518985306634600221581907797\1.3.6.1.4.1.9590.100.1.2.291621955011202146833857094874091601522
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00034_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.268859269412655083322303207990295888254\1.3.6.1.4.1.9590.100.1.2.201499455513205630518500217693628672169
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00034_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.274955931012688117617126795631068933300\1.3.6.1.4.1.9590.100.1.2.287974861112966343326395908123786241211
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00043_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.94294681410362720825065184111316689761\1.3.6.1.4.1.9590.100.1.2.375522455511603175139383410422347392769
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00047_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.155046609013709176715670803564130273583\1.3.6.1.4.1.9590.100.1.2.391876226111657492320851639130860760300
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00047_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.155046609013709176715670803564130273583\1.3.6.1.4.1.9590.100.1.2.391876226111657492320851639130860760300
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00047_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.155046609013709176715670803564130273583\1.3.6.1.4.1.9590.100.1.2.391876226111657492320851639130860760300
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00047_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.42327953211221501409627851671608189501\1.3.6.1.4.1.9590.100.1.2.93188214610698815600756310350102908043
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00047_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.42327953211221501409627851671608189501\1.3.6.1.4.1.9590.100.1.2.93188214610698815600756310350102908043
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00047_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.42327953211221501409627851671608189501\1.3.6.1.4.1.9590.100.1.2.93188214610698815600756310350102908043
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00048_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.410055731112247012036248188220256364703\1.3.6.1.4.1.9590.100.1.2.113088658712941187126679102951042396054
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00048_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.410055731112247012036248188220256364703\1.3.6.1.4.1.9590.100.1.2.113088658712941187126679102951042396054
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00048_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.285246051012141103110185857282988020948\1.3.6.1.4.1.9590.100.1.2.105968129011085973513291797982789439853
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00048_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.285246051012141103110185857282988020948\1.3.6.1.4.1.9590.100.1.2.105968129011085973513291797982789439853
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00049_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.54574932512575362039114628373141671344\1.3.6.1.4.1.9590.100.1.2.363998510013502165713496820931778815938
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00049_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.74309857012526172005930845972808775796\1.3.6.1.4.1.9590.100.1.2.104480937912142008905105345630206309467
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00060_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.111184828512638871606677733150300131839\1.3.6.1.4.1.9590.100.1.2.107813078113989584811224180480605876395
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00060_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.91476110713172979911552183463315793043\1.3.6.1.4.1.9590.100.1.2.81224121613615658336040014641017971693
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00062_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.185032347211890986400524453353693438646\1.3.6.1.4.1.9590.100.1.2.393322274613132551737979514223196972569
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00062_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.154569748312676107228097125292194099698\1.3.6.1.4.1.9590.100.1.2.363818853912156378310973075532003876069
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00063_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.279667851910350937107242584640052604603\1.3.6.1.4.1.9590.100.1.2.228098801912010422113537916701035385124
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00063_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.152210385711727196015856859430821912475\1.3.6.1.4.1.9590.100.1.2.213028272112982631512336331620101061807
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00071_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.181430762911988571208863290221301198655\1.3.6.1.4.1.9590.100.1.2.417245885012230027939057578802735850674
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00071_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.41021921311384639303213854041560085378\1.3.6.1.4.1.9590.100.1.2.260908917912584340334325958833375873776
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00078_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.190823154012137850526633568121335074864\1.3.6.1.4.1.9590.100.1.2.295998575611386490025864183312917474029
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00078_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.306022949612457168908506651110337994271\1.3.6.1.4.1.9590.100.1.2.102055444111189562121016464983795828597
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00083_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.275045398312189721027021690053923866791\1.3.6.1.4.1.9590.100.1.2.337708571111934364527685482773600796600
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00084_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.67024352911175451315025368361963496706\1.3.6.1.4.1.9590.100.1.2.379175748313156423405585484032787500736
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00084_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.241982865411994450803751325480522591993\1.3.6.1.4.1.9590.100.1.2.66112330411140340105014191773026467660
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00085_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.425328790411312933836368529101633672573\1.3.6.1.4.1.9590.100.1.2.393240561112205128707391894273067457000
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00085_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.250159549613619251135327563710983966505\1.3.6.1.4.1.9590.100.1.2.332622214912498098134724868361643196992
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00088_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.36871810712713309940991440770595552407\1.3.6.1.4.1.9590.100.1.2.385676425013059820227250013453708267714
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00088_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.79982283711568734229189019390033560357\1.3.6.1.4.1.9590.100.1.2.70693830012973314811488014530500090172
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00091_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.276168566912790030905847417793203286230\1.3.6.1.4.1.9590.100.1.2.98211941611503864916543313040642872143
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00091_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.173883331311350440241611450180057182150\1.3.6.1.4.1.9590.100.1.2.148870984211333305831203941473577179039
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00098_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.133720276312652630012472308854241552223\1.3.6.1.4.1.9590.100.1.2.128971107611361603033728268130430556677
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00098_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.327200542012342536126195193633256431673\1.3.6.1.4.1.9590.100.1.2.33861711511809892034543074661890550667
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00098_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.327200542012342536126195193633256431673\1.3.6.1.4.1.9590.100.1.2.33861711511809892034543074661890550667
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00098_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.261342561112145316326696436902397832720\1.3.6.1.4.1.9590.100.1.2.224225944413287957229090139042821529119
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00098_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.190245321812312470804798660343131087262\1.3.6.1.4.1.9590.100.1.2.318543965711217763213591571541538853788
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00098_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.190245321812312470804798660343131087262\1.3.6.1.4.1.9590.100.1.2.318543965711217763213591571541538853788
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00101_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.76934332111369453912679279361302684702\1.3.6.1.4.1.9590.100.1.2.387302091512953100939990337603904295050
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00101_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.65170910912448360731684642704279265078\1.3.6.1.4.1.9590.100.1.2.325202908012267823903213633892192510338
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00105_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.43047811412708024128566537501321526739\1.3.6.1.4.1.9590.100.1.2.8433705612119628039709943644165314222
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00105_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.321311090812789724516496203681077430902\1.3.6.1.4.1.9590.100.1.2.173470568512513530609795736530062754770
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00106_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.77769823510297036413624879371452132501\1.3.6.1.4.1.9590.100.1.2.323217412710482457939027237711644777753
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00106_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.285397839712946836108102340090893096750\1.3.6.1.4.1.9590.100.1.2.178623233311793947517899818422469606660
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.389032377711809506534963915711076669583\1.3.6.1.4.1.9590.100.1.2.372242868912771199931376088613260744366
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.389032377711809506534963915711076669583\1.3.6.1.4.1.9590.100.1.2.372242868912771199931376088613260744366
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.389032377711809506534963915711076669583\1.3.6.1.4.1.9590.100.1.2.372242868912771199931376088613260744366
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.389032377711809506534963915711076669583\1.3.6.1.4.1.9590.100.1.2.372242868912771199931376088613260744366
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.229507926611612245303276550950140392772\1.3.6.1.4.1.9590.100.1.2.226337463110875594101666175242078490747
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.229507926611612245303276550950140392772\1.3.6.1.4.1.9590.100.1.2.226337463110875594101666175242078490747
No PNG files found in ..\cbis_ddsm_png\Calc-Training_P_00112_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.229507926611612245303276550950140392772\1.3.6.1.4.1.9590.100.1.2.226337463110875594101666175242078490747

In [18]:
print(f"Total images found: {num_images}")
print(f"Images missing: {len(missing_images)}")

print(f"Total training images: {len(df)}")

Total images found: 0
Images missing: 2781
Total training images: 2781

In [19]:
# Remove rows with missing images from the DataFrame

df = df[~df['image file path'].isin(missing_images)].reset_index(drop=True)

In [20]:
from pathlib import Path


test_num_images = 0
test_missing_images = np.array([])

for path in test_df['image file path']:

    relative = Path(path)

    # Remove the placeholder filename
    folder = Path("cbis_ddsm_png") / relative.parent

    png_files = list(folder.glob("*.png"))

    if len(png_files) == 0:
        print(f"No PNG files found in {folder}")
        test_missing_images = np.append(test_missing_images, path)
        continue

    test_num_images += 1

No PNG files found in cbis_ddsm_png\Calc-Test_P_00038_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.85935434310203356712688695661986996009\1.3.6.1.4.1.9590.100.1.2.374115997511889073021386151921807063992
No PNG files found in cbis_ddsm_png\Calc-Test_P_00038_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.384159464510350889125645400702639717613\1.3.6.1.4.1.9590.100.1.2.174390361112646747718661211471328897934
No PNG files found in cbis_ddsm_png\Calc-Test_P_00038_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.177706148911820252341905176394069228468\1.3.6.1.4.1.9590.100.1.2.263861248711313923336051913560309963304
No PNG files found in cbis_ddsm_png\Calc-Test_P_00038_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.177706148911820252341905176394069228468\1.3.6.1.4.1.9590.100.1.2.263861248711313923336051913560309963304
No PNG files found in cbis_ddsm_png\Calc-Test_P_00038_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.328421320411501709324953698601549885215\1.3.6.1.4.1.9590.100.1.2.44262460211112930513355519060642708846
No PNG files found in cbis_ddsm_png\Calc-Test_P_00038_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.328421320411501709324953698601549885215\1.3.6.1.4.1.9590.100.1.2.44262460211112930513355519060642708846
No PNG files found in cbis_ddsm_png\Calc-Test_P_00041_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.69692063913639875309068650720468252275\1.3.6.1.4.1.9590.100.1.2.272917492411709393015036949944104292812
No PNG files found in cbis_ddsm_png\Calc-Test_P_00041_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.142141008410911067722208613271583980130\1.3.6.1.4.1.9590.100.1.2.214716350711587846302171252931002081387
No PNG files found in cbis_ddsm_png\Calc-Test_P_00077_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.171237778213286314004831596800955774428\1.3.6.1.4.1.9590.100.1.2.120762895113344405411143779050723940544
No PNG files found in cbis_ddsm_png\Calc-Test_P_00077_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.183241556612565531802314594842720002297\1.3.6.1.4.1.9590.100.1.2.69721320913248429509817283852233561951
No PNG files found in cbis_ddsm_png\Calc-Test_P_00077_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.15129196611219884010077462182303438195\1.3.6.1.4.1.9590.100.1.2.267340905912306939309266861160349187486
No PNG files found in cbis_ddsm_png\Calc-Test_P_00077_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.15129196611219884010077462182303438195\1.3.6.1.4.1.9590.100.1.2.267340905912306939309266861160349187486
No PNG files found in cbis_ddsm_png\Calc-Test_P_00077_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.365452443811764926000393384013009629026\1.3.6.1.4.1.9590.100.1.2.385318920211943956428747846422015934212
No PNG files found in cbis_ddsm_png\Calc-Test_P_00077_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.365452443811764926000393384013009629026\1.3.6.1.4.1.9590.100.1.2.385318920211943956428747846422015934212
No PNG files found in cbis_ddsm_png\Calc-Test_P_00100_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.230778565512681440620732773312948799985\1.3.6.1.4.1.9590.100.1.2.153667468610757963111534821171489110348
No PNG files found in cbis_ddsm_png\Calc-Test_P_00100_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.261621815911957508608887658251980280242\1.3.6.1.4.1.9590.100.1.2.15995324612513297805389764184183861099
No PNG files found in cbis_ddsm_png\Calc-Test_P_00127_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.238227987212757626039739516193166448220\1.3.6.1.4.1.9590.100.1.2.61347581410432668240174563181885281950
No PNG files found in cbis_ddsm_png\Calc-Test_P_00127_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.404823705712101112613641274052236131602\1.3.6.1.4.1.9590.100.1.2.90066757213729410240080160501989256297
No PNG files found in cbis_ddsm_png\Calc-Test_P_00132_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.194593510212058182320671200433557462264\1.3.6.1.4.1.9590.100.1.2.97077337711594266526257744642271450347
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.207673804211103557441193847251640642407\1.3.6.1.4.1.9590.100.1.2.274130392610570391808711256560834154926
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.207673804211103557441193847251640642407\1.3.6.1.4.1.9590.100.1.2.274130392610570391808711256560834154926
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.425425999111981459007730827801424873345\1.3.6.1.4.1.9590.100.1.2.160774588912073940140978200673940941357
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.425425999111981459007730827801424873345\1.3.6.1.4.1.9590.100.1.2.160774588912073940140978200673940941357
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.177361423111653944027713911481301007513\1.3.6.1.4.1.9590.100.1.2.166306213011523167100206271232508074491
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.177361423111653944027713911481301007513\1.3.6.1.4.1.9590.100.1.2.166306213011523167100206271232508074491
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.259749192511820032606351371581395160040\1.3.6.1.4.1.9590.100.1.2.330857446012977397138099882753167890565
No PNG files found in cbis_ddsm_png\Calc-Test_P_00140_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.259749192511820032606351371581395160040\1.3.6.1.4.1.9590.100.1.2.330857446012977397138099882753167890565
No PNG files found in cbis_ddsm_png\Calc-Test_P_00141_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.178857961212194190028926752161715518449\1.3.6.1.4.1.9590.100.1.2.31530197011146306721503417840497423357
No PNG files found in cbis_ddsm_png\Calc-Test_P_00141_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.270224245610185773912906395151111786420\1.3.6.1.4.1.9590.100.1.2.59895013913203402813556087471326658669
No PNG files found in cbis_ddsm_png\Calc-Test_P_00150_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.371331409111355117622350419550343065980\1.3.6.1.4.1.9590.100.1.2.114501333713829221314528651860576350917
No PNG files found in cbis_ddsm_png\Calc-Test_P_00163_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.102307995713574140823712861903467914035\1.3.6.1.4.1.9590.100.1.2.418134355612932102030136849102116704357
No PNG files found in cbis_ddsm_png\Calc-Test_P_00163_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.219084259611341474834321906141067760281\1.3.6.1.4.1.9590.100.1.2.355621977111644810605764135772022462045
No PNG files found in cbis_ddsm_png\Calc-Test_P_00164_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.198671590012596483413328889620965677973\1.3.6.1.4.1.9590.100.1.2.101282442711963955211635160453427358442
No PNG files found in cbis_ddsm_png\Calc-Test_P_00180_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.287610717311721764203396730160011631108\1.3.6.1.4.1.9590.100.1.2.313501247412013571402618592290816934705
No PNG files found in cbis_ddsm_png\Calc-Test_P_00180_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.321396330612179804323192201171828470785\1.3.6.1.4.1.9590.100.1.2.325115548612557564115565146981909824673
No PNG files found in cbis_ddsm_png\Calc-Test_P_00195_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.178135750213903258008337972962548515054\1.3.6.1.4.1.9590.100.1.2.343615285613423242513342939330313281342
No PNG files found in cbis_ddsm_png\Calc-Test_P_00195_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.381793985810299270821486811073079498503\1.3.6.1.4.1.9590.100.1.2.380273595512176626620212914250182855403
No PNG files found in cbis_ddsm_png\Calc-Test_P_00202_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.32737473111512049914158289192624777641\1.3.6.1.4.1.9590.100.1.2.178738814511944891404623704932278059093
No PNG files found in cbis_ddsm_png\Calc-Test_P_00202_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.159059499912798977416685315940491985806\1.3.6.1.4.1.9590.100.1.2.236005020611647513015797823113967432786
No PNG files found in cbis_ddsm_png\Calc-Test_P_00214_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.137523573912882333323301615572357720683\1.3.6.1.4.1.9590.100.1.2.266330922711278145820055051962759232884
No PNG files found in cbis_ddsm_png\Calc-Test_P_00214_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.137523573912882333323301615572357720683\1.3.6.1.4.1.9590.100.1.2.266330922711278145820055051962759232884
No PNG files found in cbis_ddsm_png\Calc-Test_P_00214_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.97636688910072791827259055401793701690\1.3.6.1.4.1.9590.100.1.2.9496122213546378401249829543613048892
No PNG files found in cbis_ddsm_png\Calc-Test_P_00214_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.97636688910072791827259055401793701690\1.3.6.1.4.1.9590.100.1.2.9496122213546378401249829543613048892
No PNG files found in cbis_ddsm_png\Calc-Test_P_00214_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.260524305712251372303831080133607578748\1.3.6.1.4.1.9590.100.1.2.257802487411496422520986169631379868842
No PNG files found in cbis_ddsm_png\Calc-Test_P_00223_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.146853945610803693227390929193249014373\1.3.6.1.4.1.9590.100.1.2.38417403411305189709180392301975041038
No PNG files found in cbis_ddsm_png\Calc-Test_P_00244_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.383565698912197538006474144320810912099\1.3.6.1.4.1.9590.100.1.2.336725446011932305309268778732891512151
No PNG files found in cbis_ddsm_png\Calc-Test_P_00246_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.378115250312337004138147429152188255726\1.3.6.1.4.1.9590.100.1.2.25530538411839768118282182472795553760
No PNG files found in cbis_ddsm_png\Calc-Test_P_00257_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.138480519711520954815403513652068382396\1.3.6.1.4.1.9590.100.1.2.347071301011925738002447241093455947230
No PNG files found in cbis_ddsm_png\Calc-Test_P_00257_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.409914573611683067919391940392991059926\1.3.6.1.4.1.9590.100.1.2.98676857111695015331891250542758735052
No PNG files found in cbis_ddsm_png\Calc-Test_P_00299_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.220589911711408027719817378662795765598\1.3.6.1.4.1.9590.100.1.2.273133994411552376714832534302635658142
No PNG files found in cbis_ddsm_png\Calc-Test_P_00299_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.360627140812181000302325633400741928747\1.3.6.1.4.1.9590.100.1.2.362975626410536426104116737502334904995
No PNG files found in cbis_ddsm_png\Calc-Test_P_00299_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.270688105911698227320897258811284365192\1.3.6.1.4.1.9590.100.1.2.88375747311155347030258851071324528043
No PNG files found in cbis_ddsm_png\Calc-Test_P_00315_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.39847900211195182809438409162128528951\1.3.6.1.4.1.9590.100.1.2.347338743012601624916824142262030859282
No PNG files found in cbis_ddsm_png\Calc-Test_P_00325_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.225381118011667165517633240460388031681\1.3.6.1.4.1.9590.100.1.2.381864286312364192418019132252494443296
No PNG files found in cbis_ddsm_png\Calc-Test_P_00331_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.94587276913288117014013001531510377359\1.3.6.1.4.1.9590.100.1.2.153281335513645539417766473510556793450
No PNG files found in cbis_ddsm_png\Calc-Test_P_00331_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.274672961811964168041957454202068941286\1.3.6.1.4.1.9590.100.1.2.78531327313921996726031305053323628358
No PNG files found in cbis_ddsm_png\Calc-Test_P_00344_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.383247321612538425133047909341371423843\1.3.6.1.4.1.9590.100.1.2.16538698211686486425718009862712591172
No PNG files found in cbis_ddsm_png\Calc-Test_P_00344_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.221038636911286553122543428433769386499\1.3.6.1.4.1.9590.100.1.2.219299223211070667010743548621793942263
No PNG files found in cbis_ddsm_png\Calc-Test_P_00352_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.310300550912276528928249391400745956354\1.3.6.1.4.1.9590.100.1.2.364769939511865969122167341301370556814
No PNG files found in cbis_ddsm_png\Calc-Test_P_00352_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.256541901513836436742459664780306594204\1.3.6.1.4.1.9590.100.1.2.397101994611349974417674059850771622939
No PNG files found in cbis_ddsm_png\Calc-Test_P_00353_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.145734018111291645519131313920862306101\1.3.6.1.4.1.9590.100.1.2.374083122712703142909330807542822451571
No PNG files found in cbis_ddsm_png\Calc-Test_P_00353_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.187901580911478669925012776200242918395\1.3.6.1.4.1.9590.100.1.2.204430961913085029114963861863064771359
No PNG files found in cbis_ddsm_png\Calc-Test_P_00353_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.145734018111291645519131313920862306101\1.3.6.1.4.1.9590.100.1.2.374083122712703142909330807542822451571
No PNG files found in cbis_ddsm_png\Calc-Test_P_00353_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.187901580911478669925012776200242918395\1.3.6.1.4.1.9590.100.1.2.204430961913085029114963861863064771359
No PNG files found in cbis_ddsm_png\Calc-Test_P_00368_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.308003609811708896140235956723425779820\1.3.6.1.4.1.9590.100.1.2.175382778511258946501326317242254559109
No PNG files found in cbis_ddsm_png\Calc-Test_P_00368_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.319503215512153643300238023023595618491\1.3.6.1.4.1.9590.100.1.2.6401091112997259908805705101363925774
No PNG files found in cbis_ddsm_png\Calc-Test_P_00372_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.60376963513152027018772589123150731619\1.3.6.1.4.1.9590.100.1.2.267714876311589393628890535711942443047
No PNG files found in cbis_ddsm_png\Calc-Test_P_00372_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.80570331612027159925670624090168062345\1.3.6.1.4.1.9590.100.1.2.56446728211851974029244450883139880921
No PNG files found in cbis_ddsm_png\Calc-Test_P_00390_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.422682780212684746129543550780888854247\1.3.6.1.4.1.9590.100.1.2.67473123611959273037195362662027403888
No PNG files found in cbis_ddsm_png\Calc-Test_P_00390_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.27636050111608558110247765761594906169\1.3.6.1.4.1.9590.100.1.2.358679916212113796016665468462812049600
No PNG files found in cbis_ddsm_png\Calc-Test_P_00397_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.417634930211569589030074763822962085198\1.3.6.1.4.1.9590.100.1.2.209300280410374447319412284721590506572
No PNG files found in cbis_ddsm_png\Calc-Test_P_00402_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.325159629011147920904797620932326904129\1.3.6.1.4.1.9590.100.1.2.195038125411006195533245648703882808947
No PNG files found in cbis_ddsm_png\Calc-Test_P_00402_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.158862305311323783304489460770486049839\1.3.6.1.4.1.9590.100.1.2.172660415211083198922346282250282946691
No PNG files found in cbis_ddsm_png\Calc-Test_P_00403_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.164172355312381123523986948410985369818\1.3.6.1.4.1.9590.100.1.2.308550737911523802806449145721212125433
No PNG files found in cbis_ddsm_png\Calc-Test_P_00403_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.204485836011508745902065501540691923219\1.3.6.1.4.1.9590.100.1.2.310621878711988704903716607162484515072
No PNG files found in cbis_ddsm_png\Calc-Test_P_00460_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.296568878212348566436245301113177379154\1.3.6.1.4.1.9590.100.1.2.90140760812082371129875283483750515253
No PNG files found in cbis_ddsm_png\Calc-Test_P_00460_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.339508427012094697011454647280685029289\1.3.6.1.4.1.9590.100.1.2.352549780613273821437164768190416109074
No PNG files found in cbis_ddsm_png\Calc-Test_P_00466_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.350011668613124409109651564843908171069\1.3.6.1.4.1.9590.100.1.2.3247354612054909430402543963868297656
No PNG files found in cbis_ddsm_png\Calc-Test_P_00485_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.299050269611436822102138604901211017517\1.3.6.1.4.1.9590.100.1.2.127896422011431355705216667061075429849
No PNG files found in cbis_ddsm_png\Calc-Test_P_00485_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.299050269611436822102138604901211017517\1.3.6.1.4.1.9590.100.1.2.127896422011431355705216667061075429849
No PNG files found in cbis_ddsm_png\Calc-Test_P_00485_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.299050269611436822102138604901211017517\1.3.6.1.4.1.9590.100.1.2.127896422011431355705216667061075429849
No PNG files found in cbis_ddsm_png\Calc-Test_P_00485_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.299050269611436822102138604901211017517\1.3.6.1.4.1.9590.100.1.2.127896422011431355705216667061075429849
No PNG files found in cbis_ddsm_png\Calc-Test_P_00485_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.299050269611436822102138604901211017517\1.3.6.1.4.1.9590.100.1.2.127896422011431355705216667061075429849
No PNG files found in cbis_ddsm_png\Calc-Test_P_00485_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.323204931110444933642472772080259688676\1.3.6.1.4.1.9590.100.1.2.41576445910017924501198330182143430811
No PNG files found in cbis_ddsm_png\Calc-Test_P_00495_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.20165361412203509801020579063031038923\1.3.6.1.4.1.9590.100.1.2.204340788011772153840832869381951396003
No PNG files found in cbis_ddsm_png\Calc-Test_P_00495_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.20165361412203509801020579063031038923\1.3.6.1.4.1.9590.100.1.2.204340788011772153840832869381951396003
No PNG files found in cbis_ddsm_png\Calc-Test_P_00495_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.304325810511113638229546218523083837538\1.3.6.1.4.1.9590.100.1.2.46022236911789431731325175472242267906
No PNG files found in cbis_ddsm_png\Calc-Test_P_00495_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.304325810511113638229546218523083837538\1.3.6.1.4.1.9590.100.1.2.46022236911789431731325175472242267906
No PNG files found in cbis_ddsm_png\Calc-Test_P_00497_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.279229856411469372607467262930297060238\1.3.6.1.4.1.9590.100.1.2.10934298311067781740288275432644531576
No PNG files found in cbis_ddsm_png\Calc-Test_P_00497_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.100742355113831624803390319643765691480\1.3.6.1.4.1.9590.100.1.2.70985143510653524008930802050422673389
No PNG files found in cbis_ddsm_png\Calc-Test_P_00537_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.353232060412887840613559724961749434842\1.3.6.1.4.1.9590.100.1.2.295074553711467509004234310912016105812
No PNG files found in cbis_ddsm_png\Calc-Test_P_00562_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.111155507210454361036615571531588713097\1.3.6.1.4.1.9590.100.1.2.423362291613867583614352145134188311824
No PNG files found in cbis_ddsm_png\Calc-Test_P_00562_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.111155507210454361036615571531588713097\1.3.6.1.4.1.9590.100.1.2.423362291613867583614352145134188311824
No PNG files found in cbis_ddsm_png\Calc-Test_P_00562_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.69457994312524151513979580231966793621\1.3.6.1.4.1.9590.100.1.2.38392550711685613036629925172762052505
No PNG files found in cbis_ddsm_png\Calc-Test_P_00562_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.69457994312524151513979580231966793621\1.3.6.1.4.1.9590.100.1.2.38392550711685613036629925172762052505
No PNG files found in cbis_ddsm_png\Calc-Test_P_00562_RIGHT_CC\1.3.6.1.4.1.9590.100.1.2.194327245612327574631584183283221072833\1.3.6.1.4.1.9590.100.1.2.185156161812217421816754789663493863503
No PNG files found in cbis_ddsm_png\Calc-Test_P_00562_RIGHT_MLO\1.3.6.1.4.1.9590.100.1.2.239899310610963518903279284760707938563\1.3.6.1.4.1.9590.100.1.2.398972365411034290001921322240245033267
No PNG files found in cbis_ddsm_png\Calc-Test_P_00570_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.83223259511469927522307383133522923242\1.3.6.1.4.1.9590.100.1.2.323546184912772856836256667373341364590
No PNG files found in cbis_ddsm_png\Calc-Test_P_00579_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.12359791211506399609906922340877927421\1.3.6.1.4.1.9590.100.1.2.299021344312689790125182609072928955904
No PNG files found in cbis_ddsm_png\Calc-Test_P_00589_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.99648655512190063432962093182131404583\1.3.6.1.4.1.9590.100.1.2.178203594513520416601754679041093350921
No PNG files found in cbis_ddsm_png\Calc-Test_P_00589_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.342771471811699662622463353882627418699\1.3.6.1.4.1.9590.100.1.2.147398241412716944210846493583224406915
No PNG files found in cbis_ddsm_png\Calc-Test_P_00608_LEFT_CC\1.3.6.1.4.1.9590.100.1.2.63070837510649910605859557733146564794\1.3.6.1.4.1.9590.100.1.2.27635194012994443918230980433628850921
No PNG files found in cbis_ddsm_png\Calc-Test_P_00608_LEFT_MLO\1.3.6.1.4.1.9590.100.1.2.337489285812819748708949945881582065732\1.3.6.1.4.1.9590.100.1.2.328813540111033672118264518851392096230

In [21]:
print(f"Total images found: {test_num_images}")
print(f"Images missing: {len(test_missing_images)}")

print(f"Total testing images: {len(test_df)}")

Total images found: 0
Images missing: 704
Total testing images: 704

In [22]:
test_df = test_df[~test_df['image file path'].isin(test_missing_images)].reset_index(drop=True)

In [23]:
total = len(df) + len(test_df)

print("Total:", total)
print(f"Train {len(df)} | {len(df)/total*100:.2f}%" )
print(f"Test {len(test_df)} | {len(test_df)/total*100:.2f}%" )

Total: 0

ZeroDivisionError: division by zero

In [ ]:
excess_train =  abs(len(df) - len(df) - int(total * 0.0678))

excess_train

216

In [ ]:
print("Training dataset pathology distribution:")
print(df['pathology'].value_counts(normalize=True))
print(df['pathology'].value_counts())
print()
print("Testing dataset pathology distribution:")
print(test_df['pathology'].value_counts(normalize=True))
print(test_df['pathology'].value_counts())

Training dataset pathology distribution:
pathology
0    0.588809
1    0.411191
Name: proportion, dtype: float64
pathology
0    1631
1    1139
Name: count, dtype: int64

Testing dataset pathology distribution:
pathology
0    0.587678
1    0.412322
Name: proportion, dtype: float64
pathology
0    248
1    174
Name: count, dtype: int64

In [ ]:
excess_train_benign = int(excess_train * df['pathology'].value_counts(normalize=True)[0])
excess_train_malignant = int(excess_train * df['pathology'].value_counts(normalize=True)[1])

print(f"Excess training samples: {excess_train}")
print(f"Excess training samples (benign): {excess_train_benign}")
print(f"Excess training samples (malignant): {excess_train_malignant}")

Excess training samples: 216
Excess training samples (benign): 127
Excess training samples (malignant): 88

In [ ]:
full_df = pd.concat([df, test_df], ignore_index=True)

In [ ]:
print(full_df["pathology"].isna().sum())
print(len(full_df), full_df['patient_id'].duplicated().sum())

0
3192 1743

In [ ]:
from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        full_df,
        groups=full_df["patient_id"]
    )
)

train_df = full_df.iloc[train_idx].reset_index(drop=True)
test_df = full_df.iloc[test_idx].reset_index(drop=True)

In [ ]:
print(f"Null pathology values: {full_df['pathology'].isna().sum()}")
print()

train_patients = set(train_df["patient_id"])
test_patients = set(test_df["patient_id"])

overlap = train_patients.intersection(test_patients)

print(f"Overlapping patients: {len(overlap)}")
print()

print(f"Train pathology distribution:")
print(train_df["pathology"].value_counts(normalize=True))
print(f"Test pathology distribution:")
print(test_df["pathology"].value_counts(normalize=True))

print()

total = len(train_df) + len(test_df)

print("Total:", total)
print(f"Train {len(train_df)} | {len(train_df)/total*100:.2f}%" )
print(f"Test {len(test_df)} | {len(test_df)/total*100:.2f}%" )

Null pathology values: 0

Overlapping patients: 0

Train pathology distribution:
pathology
0    0.591499
1    0.408501
Name: proportion, dtype: float64
Test pathology distribution:
pathology
0    0.577573
1    0.422427
Name: proportion, dtype: float64

Total: 3192
Train 2541 | 79.61%
Test 651 | 20.39%

In [ ]:
print(train_df["pathology"].value_counts(normalize=True))
print(train_df["pathology"].value_counts())
print(test_df["pathology"].value_counts(normalize=True))
print(test_df["pathology"].value_counts())

pathology
0    0.591499
1    0.408501
Name: proportion, dtype: float64
pathology
0    1503
1    1038
Name: count, dtype: int64
pathology
0    0.577573
1    0.422427
Name: proportion, dtype: float64
pathology
0    376
1    275
Name: count, dtype: int64

In [ ]:
print(len(train_df), len(test_df), len(train_df) + len(test_df))

2541 651 3192

In [ ]:
print(train_df['ROI mask file path'].head())

NameError: name 'train_df' is not defined

In [ ]:
train_df['image file path'] = train_df['image file path'].str[:-10]
test_df['image file path'] = test_df['image file path'].str[:-10]

print(train_df.head())
print(test_df.head())

  patient_id  breast density left or right breast image view  abnormality id  \
0    P_00005             3.0                RIGHT         CC               1
1    P_00005             3.0                RIGHT        MLO               1
2    P_00007             4.0                 LEFT         CC               1
3    P_00007             4.0                 LEFT        MLO               1
4    P_00008             1.0                 LEFT         CC               1

  abnormality type    calc type calc distribution  assessment  pathology  \
0    calcification    AMORPHOUS         CLUSTERED           3          1
1    calcification    AMORPHOUS         CLUSTERED           3          1
2    calcification  PLEOMORPHIC            LINEAR           4          0
3    calcification  PLEOMORPHIC            LINEAR           4          0
4    calcification          NaN          REGIONAL           2          0

   subtlety  \
0         3
1         3
2         4
3         4
4         3

                                                                                                                                                      image file path  \
0    Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/
1  Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/
2    Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/
3   Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/
4    Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/

                                                                                                                                                           cropped image file path  \
0  Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000001.dcm\n
1  Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000001.dcm\n
2   Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000001.dcm\n
3   Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000001.dcm\n
4   Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000001.dcm\n

                                                                                                                                                              ROI mask file path  \
0  Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000000.dcm
1  Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000000.dcm
2   Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000000.dcm
3   Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000000.dcm
4   Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000000.dcm

   breast_density mass shape mass margins
0             NaN        NaN          NaN
1             NaN        NaN          NaN
2             NaN        NaN          NaN
3             NaN        NaN          NaN
4             NaN        NaN          NaN
  patient_id  breast density left or right breast image view  abnormality id  \
0    P_00019             4.0                RIGHT        MLO               1
1    P_00019             4.0                RIGHT         CC               1
2    P_00028             4.0                 LEFT        MLO               1
3    P_00078             2.0                 LEFT         CC               1
4    P_00078             2.0                 LEFT        MLO               1

  abnormality type    calc type calc distribution  assessment  pathology  \
0    calcification  PLEOMORPHIC         CLUSTERED           4          0
1    calcification  PLEOMORPHIC         CLUSTERED           4          0
2    calcification  PLEOMORPHIC         CLUSTERED           4          0
3    calcification  PLEOMORPHIC         CLUSTERED           4          1
4    calcification  PLEOMORPHIC         CLUSTERED           4          1

   subtlety  \
0         2
1         2
2         1
3         1
4         1

                                                                                                                                                      image file path  \
0  Calc-Training_P_00019_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.402862878710879755318440884650362135937/1.3.6.1.4.1.9590.100.1.2.211427675111583558805605682400609571318/
1    Calc-Training_P_00019_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.86372204413773963300916773660922384889/1.3.6.1.4.1.9590.100.1.2.326956207912458716509788527682547540915/
2    Calc-Training_P_00028_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.43782707412115361525617363602457775937/1.3.6.1.4.1.9590.100.1.2.384733400713300334228962042161417756433/
3    Calc-Training_P_00078_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.190823154012137850526633568121335074864/1.3.6.1.4.1.9590.100.1.2.295998575611386490025864183312917474029/
4   Calc-Training_P_00078_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.306022949612457168908506651110337994271/1.3.6.1.4.1.9590.100.1.2.102055444111189562121016464983795828597/

                                                                                                                                                            cropped image file path  \
0  Calc-Training_P_00019_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.321333206211434894702467255612410089563/1.3.6.1.4.1.9590.100.1.2.141269558913652553006787176281528676980/000001.dcm\n
1   Calc-Training_P_00019_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.180383217411474965117355808620907562244/1.3.6.1.4.1.9590.100.1.2.181380004612430571924629395230074095682/000001.dcm\n
2    Calc-Training_P_00028_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.304652523211635217600539833652824421473/1.3.6.1.4.1.9590.100.1.2.81595047412515733434402090860388891176/000001.dcm\n
3    Calc-Training_P_00078_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.242949641311158559519731723554198328959/1.3.6.1.4.1.9590.100.1.2.118041398411548857626787122023801406978/000001.dcm\n
4   Calc-Training_P_00078_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.264285469011851276239740371670628123716/1.3.6.1.4.1.9590.100.1.2.288247537612268788818218599712870677562/000001.dcm\n

                                                                                                                                                               ROI mask file path  \
0  Calc-Training_P_00019_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.321333206211434894702467255612410089563/1.3.6.1.4.1.9590.100.1.2.141269558913652553006787176281528676980/000000.dcm
1   Calc-Training_P_00019_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.180383217411474965117355808620907562244/1.3.6.1.4.1.9590.100.1.2.181380004612430571924629395230074095682/000000.dcm
2    Calc-Training_P_00028_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.304652523211635217600539833652824421473/1.3.6.1.4.1.9590.100.1.2.81595047412515733434402090860388891176/000000.dcm
3    Calc-Training_P_00078_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.242949641311158559519731723554198328959/1.3.6.1.4.1.9590.100.1.2.118041398411548857626787122023801406978/000000.dcm
4   Calc-Training_P_00078_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.264285469011851276239740371670628123716/1.3.6.1.4.1.9590.100.1.2.288247537612268788818218599712870677562/000000.dcm

   breast_density mass shape mass margins
0             NaN        NaN          NaN
1             NaN        NaN          NaN
2             NaN        NaN          NaN
3             NaN        NaN          NaN
4             NaN        NaN          NaN

In [ ]:
train_df_subset = train_df[['patient_id', 'pathology', 'image file path']]
test_df_subset = test_df[['patient_id', 'pathology', 'image file path']]

print(train_df_subset.head())
print(test_df_subset.head())

  patient_id  pathology  \
0    P_00005          1
1    P_00005          1
2    P_00007          0
3    P_00007          0
4    P_00008          0

                                                                                                                                                      image file path
0    Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/
1  Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/
2    Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/
3   Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/
4    Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/
  patient_id  pathology  \
0    P_00019          0
1    P_00019          0
2    P_00028          0
3    P_00078          1
4    P_00078          1

                                                                                                                                                      image file path
0  Calc-Training_P_00019_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.402862878710879755318440884650362135937/1.3.6.1.4.1.9590.100.1.2.211427675111583558805605682400609571318/
1    Calc-Training_P_00019_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.86372204413773963300916773660922384889/1.3.6.1.4.1.9590.100.1.2.326956207912458716509788527682547540915/
2    Calc-Training_P_00028_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.43782707412115361525617363602457775937/1.3.6.1.4.1.9590.100.1.2.384733400713300334228962042161417756433/
3    Calc-Training_P_00078_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.190823154012137850526633568121335074864/1.3.6.1.4.1.9590.100.1.2.295998575611386490025864183312917474029/
4   Calc-Training_P_00078_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.306022949612457168908506651110337994271/1.3.6.1.4.1.9590.100.1.2.102055444111189562121016464983795828597/

In [ ]:
# train_df_subset.to_csv("train_df.csv", index=False)
# test_df_subset.to_csv("test_df.csv", index=False)